### ISSUE TITLE
Invalid artifact pages mapping

### ISSUE THREAD

**Issue by ledsoft** [kbss-cvut/kbss-website#1]
Navigating to artifact detail pages such as __OntoMind__ or __OWLDiff__ leads to 404 page. The problem is that their URL is mapped incorrectly, so instead of , e.g., [https://kbss-cvut.github.io/kbss-website/artifacts/sw/owldiff](https://kbss-cvut.github.io/kbss-website/artifacts/sw/owldiff), it leads to [https://kbss-cvut.github.io/artifacts/sw/owldiff](https://kbss-cvut.github.io/artifacts/sw/owldiff).

**Comment by MichalMed** [comment]
it was solved by serving jekyll on localhost, but GH pages still do not show it right
