### ISSUE TITLE
Create pages for teaching

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/kbss-website#28]
@MichalMed You requested me to add some pages to teaching. I am ok have-ing such page, but I believe it is not very important (thus I would be ok even if it is not accessible from our homepage).

Nevertheless, in case we want to have it like you proposed, I would design it as follows:
1) A Picture something relevant for enterprise systems + sematic web ??
2) I would mention only that our main teaching scope is "Semantic web+Enterprise architectures in JAVA".   And nothing but reference [EAR](https://fel.cvut.cz/cz/education/rozvrhy-ng/public/html/predmety/31/30/p3130406.html)) and [OSW](https://fel.cvut.cz/cz/education/bk/predmety/58/33/p5833706.html).
3) There is also option to mention that we participate in teaching: [SWA](https://fel.cvut.cz/cz/education/bk/predmety/48/79/p4879206.html) and DBS?.

In addition, in case we go this direction, we could include some nice outputs of students !? But again it should be rather links to pages which hosts the subject.

Alternative option is to have teaching activities only next to each person.

**Comment by ledsoft** [comment]
@blcham Can this be closed? There is a [page](https://kbss.felk.cvut.cz/web/teaching) for teaching and it covers pretty much everything you specify in the issue description.

**Comment by blcham** [comment]
@ledsoft sure, thanks
