### ISSUE TITLE
Change picture of bulb for teachning within kbss homepage

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/kbss-website#47]
There are 2 bulbs on the home page. It would be nice to have e.g. blackbox instead for teaching.

**Comment by blcham** [comment]
Hehe, yes `blackboard`, sorry :) -- we talked about it during the kbss meeting so I was not paying too much attention while writing the ticket.

**Comment by MichalMed** [comment]
https://unsplash.com/s/photos/blackbox - nice, just not sure how it relates to teaching

**Comment by MichalMed** [comment]
@blcham check PR, merge and eventually close

**Comment by MichalMed** [comment]
pic changed, optimized other pictures size
