### ISSUE TITLE
Links to presentations are not public

### ISSUE THREAD

**Issue by MichalMed** [kbss-cvut/kbss-website#50]
Links to the presentations at adobecloud are restricted to CTU accounts. It shall be made public.

**Comment by MichalMed** [comment]
https://documentcloud.adobe.com/gsuiteintegration/index.html?state=%7B%22ids%22%3A%5B%221JxvTRhME_5Ecprk_qcegegYUoU49yGN9%22%5D%2C%22action%22%3A%22open%22%2C%22userId%22%3A%22100616406588850202743%22%2C%22resourceKeys%22%3A%7B%7D%7D and https://documentcloud.adobe.com/gsuiteintegration/index.html?state=%7B%22ids%22%3A%5B%221ZKqIy4CdVWQh6bD5MepahdqttsSB21Bm%22%5D%2C%22action%22%3A%22open%22%2C%22userId%22%3A%22100616406588850202743%22%2C%22resourceKeys%22%3A%7B%7D%7D in Janas and Max's Open Mic Sessions

**Comment by ledsoft** [comment]
@MichalMed I propose to close this issue. I can't even access the files with my CTU account and it is highly unlikely that Jana is going to fix it. All other OpenMic slides are in a shared Google Drive folder that is accessible to anyone with a link, so I consider this problem resolved.

**Comment by ledsoft** [comment]
@MichalMed @blcham Once again, I propose to close this issue.
